config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'cups#index'

  resources :cups, only: %i[index show], param: :cup
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cup.rb
class Cup < ApplicationRecord
  def self.filenames
    Dir.entries("./app/assets/images/cups").reject { |file| File.directory? file }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def not_found
    raise ActionController::RoutingError, 'Not Found'
  end
end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
  def index; end

  def show
    @cup = cup_from_cup_param
  end

  private

  def cup_from_cup_param
    params.permit(:cup)[:cup].gsub('dot', '.')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/cups/index.html.erb
<h1>Cups and the Rails JPEG issue</h1>

There are a lot of cup images in this project. I googled for cups and chose ones I liked, for my side project. Some of them happened to be jpeg files. These ones cause issues in production environments (Heroku).

The issue occurs in production environments, not locally.

<br/>
<% Cup.filenames.each do |cup| %>
  <br/>
  <%# Replace . with 'dot' so that I can pass the filename as a param %>
  <%= link_to cup, cup_path(cup: cup.gsub('.', 'dot')) %>
<% end %>

app/views/cups/show.html.erb
<h1>You are viewing the cup called <%= @cup %></h1>

<%= image_tag("cups/#{@cup}", height: '500', alt: 'This is a cup.') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameOfCups</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>